version: "3.7"
services:
  db:
    image: mysql:8
    hostname: mysql
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_HOST=${DB_HOST}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./:/mysql
  api:
    container_name: fluxo-caixa
    build: .
    command: mvn clean spring-boot:run -Dspring-boot.run.profiles=docker
    ports:
      - "8000:8000"
    volumes:
      - ../:/api-fluxo-caixa
    depends_on:
      - db
